#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Produces lib/browser/tag.fi -- the FIXED name table of the tree building.

A WORKBENCH, NOT A PRODUCT: there is no parser logic here, only the list of
the names the HTML standard mentions by name, and their order. Because the
order is fixed, the atom id of every known name is a compile-time
constant (`M_DIV`, `M_TABLE`, ...) -- the tree building then compares
`u32` against `u32` instead of character against character.

Usage:  python3 tools/html/gen_names.py
"""

import os

# The order = the atom id (1-based). Do NOT re-sort, only append at the
# end -- otherwise all the constants change.
NAMEN = [
    # --- basic skeleton
    "html", "head", "body", "frameset", "frame", "noframes", "title",
    # --- "in head"
    "base", "basefont", "bgsound", "link", "meta", "style", "script",
    "noscript", "template",
    # --- block elements ("in body", group address/div/...)
    "address", "article", "aside", "blockquote", "center", "details",
    "dialog", "dir", "div", "dl", "dt", "dd", "fieldset", "figcaption",
    "figure", "footer", "header", "hgroup", "main", "menu", "nav", "ol",
    "p", "search", "section", "summary", "ul",
    # --- headings
    "h1", "h2", "h3", "h4", "h5", "h6",
    # --- special cases with a rule of their own
    "pre", "listing", "form", "li", "plaintext", "button",
    # --- formatting elements (list of active formatting elements)
    "a", "b", "big", "code", "em", "font", "i", "nobr", "s", "small",
    "strike", "strong", "tt", "u",
    # --- elements with a marker in the formatting list
    "applet", "marquee", "object",
    # --- tables
    "table", "caption", "colgroup", "col", "tbody", "tfoot", "thead",
    "tr", "td", "th",
    # --- empty elements
    "area", "br", "embed", "img", "keygen", "wbr", "param", "source",
    "track", "hr", "input",
    # --- text/raw text elements
    "textarea", "xmp", "iframe", "noembed",
    # --- select
    "select", "option", "optgroup",
    # --- ruby
    "rb", "rt", "rtc", "rp",
    # --- foreign content (only needed as a namespace marker, round 54)
    "math", "svg", "mi", "mo", "mn", "ms", "mtext", "annotation-xml",
    "foreignObject", "desc",
    # --- renamed by the tree building
    "image",
    # --- attribute names the tree building reads itself
    "type", "id", "class", "href", "src", "name", "action", "prompt",
    # --- added later (the order before that stays unchanged)
    "ruby",
]

HEAD = '''// lib/browser/tag.fi -- GENERATED by tools/html/gen_names.py.
// DO NOT EDIT BY HAND. The source of the order is the script.
//
// The fixed name table of the tree building: {n} names whose atom id
// (1..{n}) is settled at compile time. `namen_init` enters them in exactly
// this order into the table, which is why `M_DIV == 25` and so
// on holds. Everything beyond that (own element names, arbitrary
// attribute names) gets an id > {n} at its first appearance.

import html.mem

export {{ M_LETZTES_FEST, tab_bytes, {consts} }}

'''


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    target = os.path.join(root, "lib", "browser", "tag.fi")

    if len(set(NAMEN)) != len(NAMEN):
        dupes = [x for x in NAMEN if NAMEN.count(x) > 1]
        raise SystemExit("duplicate names: %s" % sorted(set(dupes)))

    def konst(name):
        return "M_" + name.upper().replace("-", "_")

    consts = ", ".join(konst(x) for x in NAMEN)
    text = " ".join(NAMEN)
    raw = text.encode("ascii")

    out = [HEAD.format(n=len(NAMEN), consts=consts)]
    out.append("const M_LETZTES_FEST: u32 = %d\n\n" % len(NAMEN))
    for i, name in enumerate(NAMEN, start=1):
        out.append("const %s: u32 = %d\n" % (konst(name), i))
    out.append("\n")
    out.append(
        "// The names, separated by a space. `namen_init` splits them.\n"
        "// A string literal has the type `[u8; N]` in Firn (SPEC 8,\n"
        "// tests/570_string_literals.fi), which is why the length is written\n"
        "// out here -- the script computes it.\n"
        "#[no_gc]\n"
        "fn tab_bytes(out: *mut mem.Buf) {\n"
    )
    out.append('    var t: [u8; %d] = "%s"\n' % (len(raw), text))
    out.append("    var i: usize = 0\n")
    out.append("    while i < %d {\n" % len(raw))
    out.append("        mem.buf_push(out, t[i])\n")
    out.append("        i = i + 1\n")
    out.append("    }\n")
    out.append("}\n")

    with open(target, "w", encoding="utf-8") as fh:
        fh.write("".join(out))
    print("written: %s (%d names, %d bytes of text)" % (target, len(NAMEN), len(raw)))


if __name__ == "__main__":
    main()
