#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""tools/js/gen_unicode_id.py -- generate lib/js/unicode_id.fi.

ECMA-262 12.7.1 builds identifiers on the Unicode properties ID_Start and
ID_Continue.  Firn has no global arrays (SPEC 14.1 item 5: no global
variables, `const` only for scalars), so the tables cannot be written down
as data.  They come into being at run time instead: a generated function
pushes the range bounds into a `mem.CpBuf` once, and the lexer searches
that buffer binarily.

The property data come from the `unicodedata` module of the Python that
runs this script; the Unicode version is written into the generated file so
that the table cannot silently change its meaning.  This script is a TOOL,
not part of the engine -- the generated Firn file is what gets compiled,
and it contains no foreign code.

Usage:  python3 tools/js/gen_unicode_id.py > lib/js/unicode_id.fi
"""
import sys
import unicodedata

# ECMA-262: ID_Start = L* + Nl + Other_ID_Start, ID_Continue additionally
# Mn + Mc + Nd + Pc + Other_ID_Continue.
OTHER_ID_START = {0x1885, 0x1886, 0x2118, 0x212E, 0x309B, 0x309C}
OTHER_ID_CONTINUE = {0x00B7, 0x0387, 0x19DA} | set(range(0x1369, 0x1372))

START_CATS = {"Lu", "Ll", "Lt", "Lm", "Lo", "Nl"}
CONT_CATS = START_CATS | {"Mn", "Mc", "Nd", "Pc"}

MAX = 0x110000


def ranges(pred):
    out = []
    lo = None
    for cp in range(MAX):
        if pred(cp):
            if lo is None:
                lo = cp
        else:
            if lo is not None:
                out.append((lo, cp - 1))
                lo = None
    if lo is not None:
        out.append((lo, MAX - 1))
    return out


def is_start(cp):
    if cp < 0x80:
        return False          # ASCII is decided directly in the lexer
    return unicodedata.category(chr(cp)) in START_CATS or cp in OTHER_ID_START


def is_cont(cp):
    if cp < 0x80:
        return False
    if cp in (0x200C, 0x200D):   # ZWNJ / ZWJ -- ECMA-262 adds both
        return True
    return (unicodedata.category(chr(cp)) in CONT_CATS
            or cp in OTHER_ID_START or cp in OTHER_ID_CONTINUE)


def emit(name, rs, out):
    out.append("// %d ranges." % len(rs))
    out.append("fn %s(out: *mut mem.CpBuf) {" % name)
    for lo, hi in rs:
        out.append("    mem.cp_push(out, 0x%X as u32)" % lo)
        out.append("    mem.cp_push(out, 0x%X as u32)" % hi)
    out.append("}")
    out.append("")


def main():
    start = ranges(is_start)
    cont = ranges(is_cont)
    out = []
    out.append("// lib/js/unicode_id.fi -- GENERATED by tools/js/gen_unicode_id.py.")
    out.append("// Do not edit by hand.")
    out.append("//")
    out.append("// The code point ranges of the Unicode properties ID_Start and")
    out.append("// ID_Continue that ECMA-262 12.7.1 refers to, for code points >= 0x80;")
    out.append("// ASCII is decided directly in the lexer.  ZWNJ (U+200C) and ZWJ")
    out.append("// (U+200D) are part of ID_Continue here, as ECMA-262 prescribes.")
    out.append("//")
    out.append("// Unicode version of the generator: %s" % unicodedata.unidata_version)
    out.append("// ID_Start ranges: %d, ID_Continue ranges: %d" % (len(start), len(cont)))
    out.append("import html.mem")
    out.append("")
    out.append("export { id_start_fill, id_continue_fill,")
    out.append("         ID_START_RANGES, ID_CONTINUE_RANGES }")
    out.append("")
    out.append("const ID_START_RANGES: usize = %d" % len(start))
    out.append("const ID_CONTINUE_RANGES: usize = %d" % len(cont))
    out.append("")
    emit("id_start_fill", start, out)
    emit("id_continue_fill", cont, out)
    sys.stdout.write("\n".join(out))


main()
