#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""tools/ucd/expand_tables.py -- writes tools/ucd/gen_ucd.fi.

WHAT THIS SCRIPT DOES **NOT** DO: it does not read a single Unicode
property. It knows nothing about the UCD -- not one category name, not one
code point, not one case mapping. It repeats two `comptime` blocks with a
different octet window each, and it picks the window boundaries so that
every one of them lies on a line start and never between a `<..., First>`
line and its `<..., Last>` partner.

WHY SEVERAL BLOCKS AND NOT ONE: `compiler/src/comptime.rs` allows
`MAX_STEPS = 2_000_000` executed statements per `comptime` block (SPEC
14.1.comptime, "a comptime must not hang the compiler"). A fresh
interpreter is built per block, so the budget applies per block.
`UnicodeData.txt` has 2,198,209 octets and this round parses more of every
line than round 85 did (the simple case mappings in fields 12 and 13 on top
of the general category in field 2), so it gets more windows.

The whole reading of the UCD -- hexadecimal code points, the name field,
the general category, the `First>`/`Last>` range convention, the two case
mapping fields, and the property lines of `DerivedCoreProperties.txt` --
happens inside the `comptime` blocks, i.e. **in Firn, in the compiler**.
This script supplies numbers.

Usage:
    python3 tools/ucd/expand_tables.py           # write gen_ucd.fi
    python3 tools/ucd/expand_tables.py --check   # only check it is current
"""
import bisect
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UCD = os.path.join(HERE, "UnicodeData.txt")
DCP = os.path.join(HERE, "DerivedCoreProperties.txt")
OUT = os.path.join(HERE, "gen_ucd.fi")
CHUNKS_UCD = 16
CHUNKS_DCP = 8


def boundaries(data, chunks, forbid_after_first=False):
    """`chunks` windows, every boundary on a line start."""
    n = len(data)
    starts = []
    forbidden = set()
    off = 0
    for line in data.split(b"\n"):
        starts.append(off)
        if forbid_after_first:
            fields = line.split(b";")
            if len(fields) > 2 and fields[1].endswith(b", First>"):
                # the NEXT line is the matching `, Last>` -- never split here
                forbidden.add(off + len(line) + 1)
        off += len(line) + 1
    bounds = [0]
    for k in range(1, chunks):
        target = n * k // chunks
        idx = bisect.bisect_left(starts, target)
        while starts[idx] in forbidden:
            idx += 1
        bounds.append(starts[idx])
    bounds.append(n)
    return bounds


HEAD = '''// expect_exit: 0
// tools/ucd/gen_ucd.fi -- ACCEPTANCE ITEM 6, the reading half.
//
// GENERATED by tools/ucd/expand_tables.py -- do not edit by hand, edit the
// script. The script contributes %(nucd)d + %(ndcp)d octet offsets and nothing
// else; every line of Unicode data below is read and interpreted by the
// COMPILER, at compile time, out of `comptime` blocks.
//
// What happens here:
//
//   * `file_size`/`file_byte` (SPEC 14.1.comptime, round 14) read the real
//     `UnicodeData.txt` (%(ubytes)d octets, %(ulines)d lines) and
//     `DerivedCoreProperties.txt` (%(dbytes)d octets, %(dlines)d lines) of
//     the Unicode Character Database. Both sums are pinned in
//     tools/ucd/UCD.sha256.
//   * the blocks over `UnicodeData.txt` parse field 0 (code point,
//     hexadecimal), field 1 (name, for the `<..., First>` / `<..., Last>`
//     range convention), field 2 (general category) and the fields 12 and 13
//     (simple upper and lower case mapping). Neighbouring code points with
//     the same category are coalesced into one range.
//   * the blocks over `DerivedCoreProperties.txt` parse the property lines
//     `lo..hi ; ID_Start` and `lo..hi ; ID_Continue` -- the properties
//     ECMA-262 12.7.1 builds JavaScript identifiers on. `XID_Start` and
//     `XID_Continue` begin with an `X` and are therefore NOT matched; that
//     is what the first octet of the comparison is for.
//   * `emit_raw`/`emit_number` (round 13) write Firn source text out of it,
//     which the SAME compilation run lexes, parses, type checks and
//     compiles.
//
// WHAT THIS PROGRAM IS FOR: it prints what the compiler read, as a table
// with one line per entry -- and `tools/ucd/pack.fi` turns that into the
// multi stage table `generated/unicode_tables.fi`. The split exists because
// `comptime` has integers and bools and nothing else (no arrays, SPEC
// 14.1.comptime): a table with deduplicated blocks cannot be built there.
// Reading the UCD is what the acceptance item asks of the compiler, and
// that happens here.
//
// The output format, one line each:
//
//   C <lo> <hi> <Xy>     general category of a code point range
//   S <lo> <hi>          ID_Start
//   I <lo> <hi>          ID_Continue
//   U <cp> <target>      simple upper case mapping
//   L <cp> <target>      simple lower case mapping
//
// SECURITY (SPEC 14.1.comptime): the path is relative to the root source
// file, without `..` and without a leading `/` -- which is why the data
// files lie next to this one.

// ---------------------------------------------------------------- output

// Writes the decimal digits of `x` into `buf` from `n` on and returns the
// new end.
fn num(buf: *mut u8, n: usize, x: i64) -> usize {
    var tmp: [u8; 24] = [0; 24]
    var m: usize = 0
    var v: i64 = x
    if v == 0 {
        tmp[0] = 48
        m = 1
    }
    while v > 0 {
        tmp[m] = (v %% 10) as u8 + 48
        v = v / 10
        m = m + 1
    }
    var i: usize = 0
    var out: usize = n
    while i < m {
        *((buf as usize + out) as *mut u8) = tmp[m - 1 - i]
        out = out + 1
        i = i + 1
    }
    return out
}

// "T a b\\n" -- the tag, two numbers.
fn pr(tag: u8, a: i64, b: i64) {
    var buf: [u8; 64] = [0; 64]
    let p: *mut u8 = &buf[0]
    var n: usize = 0
    buf[0] = tag
    n = 1
    buf[1] = 32
    n = 2
    n = num(p, n, a)
    *((p as usize + n) as *mut u8) = 32
    n = n + 1
    n = num(p, n, b)
    *((p as usize + n) as *mut u8) = 10
    n = n + 1
    syscall(1, 1, p, n as i64)
}

// "C a b Xy\\n" -- the category as its two letters, as they stand in the UCD.
fn prc(a: i64, b: i64, cat: i64) {
    var buf: [u8; 64] = [0; 64]
    let p: *mut u8 = &buf[0]
    var n: usize = 0
    buf[0] = 67
    n = 1
    buf[1] = 32
    n = 2
    n = num(p, n, a)
    *((p as usize + n) as *mut u8) = 32
    n = n + 1
    n = num(p, n, b)
    *((p as usize + n) as *mut u8) = 32
    n = n + 1
    *((p as usize + n) as *mut u8) = (cat / 256) as u8
    n = n + 1
    *((p as usize + n) as *mut u8) = (cat %% 256) as u8
    n = n + 1
    *((p as usize + n) as *mut u8) = 10
    n = n + 1
    syscall(1, 1, p, n as i64)
}
'''

UBLOCK = '''
// --------------------------------------- UnicodeData block %(k)d: %(start)d .. %(end)d
comptime {
    let n: i64 = file_size("UnicodeData.txt")
    var i: i64 = %(start)d
    var seen: i64 = 0
    var ranges: i64 = 0
    var maps: i64 = 0
    var lo: i64 = 0 - 1
    var hi: i64 = 0 - 1
    var cat: i64 = 0
    var pending: i64 = 0 - 1
    emit_raw("fn ucd_dump_%(k)d() {\\n")
    while i < n {
        if i >= %(end)d { break }
        // ---- field 0: the code point, hexadecimal
        var cp: i64 = 0
        var digits: i64 = 0
        while i < n {
            let c: i64 = file_byte("UnicodeData.txt", i)
            var dg: i64 = 0 - 1
            if c >= 48 { if c <= 57 { dg = c - 48 } }
            if c >= 65 { if c <= 70 { dg = c - 55 } }
            if c >= 97 { if c <= 102 { dg = c - 87 } }
            if dg < 0 { break }
            cp = cp * 16 + dg
            digits = digits + 1
            i = i + 1
        }
        // ---- field 1: the name (only its last octets matter)
        i = i + 1
        let name_start: i64 = i
        while i < n {
            if file_byte("UnicodeData.txt", i) == 59 { break }
            i = i + 1
        }
        let name_end: i64 = i
        i = i + 1
        // ---- field 2: the general category, two letters
        let a: i64 = file_byte("UnicodeData.txt", i)
        let b: i64 = file_byte("UnicodeData.txt", i + 1)
        let this_cat: i64 = a * 256 + b
        // ---- the rest of the line, counting the semicolons: field 12 is
        //      the simple upper case mapping, field 13 the lower one.
        var semis: i64 = 0
        var upper: i64 = 0
        var lower: i64 = 0
        while i < n {
            let c: i64 = file_byte("UnicodeData.txt", i)
            if c == 10 { break }
            if c == 59 {
                semis = semis + 1
                if semis == 10 {
                    var j: i64 = i + 1
                    while j < n {
                        let h: i64 = file_byte("UnicodeData.txt", j)
                        var dg: i64 = 0 - 1
                        if h >= 48 { if h <= 57 { dg = h - 48 } }
                        if h >= 65 { if h <= 70 { dg = h - 55 } }
                        if h >= 97 { if h <= 102 { dg = h - 87 } }
                        if dg < 0 { break }
                        upper = upper * 16 + dg
                        j = j + 1
                    }
                }
                if semis == 11 {
                    var j2: i64 = i + 1
                    while j2 < n {
                        let h2: i64 = file_byte("UnicodeData.txt", j2)
                        var dg2: i64 = 0 - 1
                        if h2 >= 48 { if h2 <= 57 { dg2 = h2 - 48 } }
                        if h2 >= 65 { if h2 <= 70 { dg2 = h2 - 55 } }
                        if h2 >= 97 { if h2 <= 102 { dg2 = h2 - 87 } }
                        if dg2 < 0 { break }
                        lower = lower * 16 + dg2
                        j2 = j2 + 1
                    }
                }
            }
            i = i + 1
        }
        i = i + 1
        if digits > 0 {
            seen = seen + 1
            // `, First>` (8 octets) and `, Last>` (7 octets) -- the range
            // convention of the UCD, recognised in the file itself.
            var is_first: i64 = 0
            var is_last: i64 = 0
            if name_end - name_start >= 8 {
                if file_byte("UnicodeData.txt", name_end - 8) == 44 {
                    if file_byte("UnicodeData.txt", name_end - 6) == 70 {
                        if file_byte("UnicodeData.txt", name_end - 1) == 62 {
                            is_first = 1
                        }
                    }
                }
            }
            if name_end - name_start >= 7 {
                if file_byte("UnicodeData.txt", name_end - 7) == 44 {
                    if file_byte("UnicodeData.txt", name_end - 5) == 76 {
                        if file_byte("UnicodeData.txt", name_end - 1) == 62 {
                            is_last = 1
                        }
                    }
                }
            }
            if upper > 0 {
                emit_raw("    pr(85, ")
                emit_number(cp)
                emit_raw(", ")
                emit_number(upper)
                emit_raw(")\\n")
                maps = maps + 1
            }
            if lower > 0 {
                emit_raw("    pr(76, ")
                emit_number(cp)
                emit_raw(", ")
                emit_number(lower)
                emit_raw(")\\n")
                maps = maps + 1
            }
            var entry_lo: i64 = cp
            var entry_hi: i64 = cp
            var hold: i64 = 0
            if is_first == 1 {
                pending = cp
                hold = 1
            }
            if is_last == 1 {
                entry_lo = pending
                entry_hi = cp
                pending = 0 - 1
            }
            if hold == 0 {
                var merged: i64 = 0
                if lo >= 0 {
                    if cat == this_cat {
                        if entry_lo == hi + 1 {
                            hi = entry_hi
                            merged = 1
                        }
                    }
                }
                if merged == 0 {
                    if lo >= 0 {
                        emit_raw("    prc(")
                        emit_number(lo)
                        emit_raw(", ")
                        emit_number(hi)
                        emit_raw(", ")
                        emit_number(cat)
                        emit_raw(")\\n")
                        ranges = ranges + 1
                    }
                    lo = entry_lo
                    hi = entry_hi
                    cat = this_cat
                }
            }
        }
    }
    if lo >= 0 {
        emit_raw("    prc(")
        emit_number(lo)
        emit_raw(", ")
        emit_number(hi)
        emit_raw(", ")
        emit_number(cat)
        emit_raw(")\\n")
        ranges = ranges + 1
    }
    emit_raw("}\\n")
    emit_raw("const UCD_RANGES_%(k)d: i64 = ")
    emit_number(ranges)
    emit_raw("\\nconst UCD_LINES_%(k)d: i64 = ")
    emit_number(seen)
    emit_raw("\\nconst UCD_MAPS_%(k)d: i64 = ")
    emit_number(maps)
    emit_raw("\\nconst UCD_END_%(k)d: i64 = ")
    emit_number(i)
    emit_raw("\\n")
}
'''

DBLOCK = '''
// ------------------------------ DerivedCoreProperties block %(k)d: %(start)d .. %(end)d
comptime {
    let n: i64 = file_size("DerivedCoreProperties.txt")
    var i: i64 = %(start)d
    var lines: i64 = 0
    var hits: i64 = 0
    emit_raw("fn dcp_dump_%(k)d() {\\n")
    while i < n {
        if i >= %(end)d { break }
        lines = lines + 1
        // ---- the first field: `lo` or `lo..hi`, hexadecimal
        var lo: i64 = 0
        var digits: i64 = 0
        while i < n {
            let c: i64 = file_byte("DerivedCoreProperties.txt", i)
            var dg: i64 = 0 - 1
            if c >= 48 { if c <= 57 { dg = c - 48 } }
            if c >= 65 { if c <= 70 { dg = c - 55 } }
            if c >= 97 { if c <= 102 { dg = c - 87 } }
            if dg < 0 { break }
            lo = lo * 16 + dg
            digits = digits + 1
            i = i + 1
        }
        var hi: i64 = lo
        if digits > 0 {
            if file_byte("DerivedCoreProperties.txt", i) == 46 {
                i = i + 2
                hi = 0
                while i < n {
                    let c2: i64 = file_byte("DerivedCoreProperties.txt", i)
                    var dg2: i64 = 0 - 1
                    if c2 >= 48 { if c2 <= 57 { dg2 = c2 - 48 } }
                    if c2 >= 65 { if c2 <= 70 { dg2 = c2 - 55 } }
                    if c2 >= 97 { if c2 <= 102 { dg2 = c2 - 87 } }
                    if dg2 < 0 { break }
                    hi = hi * 16 + dg2
                    i = i + 1
                }
            }
            // ---- to the `;`, then over the blanks: there stands the name
            var ok: i64 = 1
            while i < n {
                let c3: i64 = file_byte("DerivedCoreProperties.txt", i)
                if c3 == 59 { break }
                if c3 == 10 {
                    ok = 0
                    break
                }
                i = i + 1
            }
            if ok == 1 {
                i = i + 1
                while i < n {
                    if file_byte("DerivedCoreProperties.txt", i) != 32 { break }
                    i = i + 1
                }
                // `ID_Start` = 73 68 95 83 116 97 114 116, then a blank.
                // `XID_Start` begins with 88 and is therefore not matched.
                var start_p: i64 = 0
                var cont_p: i64 = 0
                if file_byte("DerivedCoreProperties.txt", i) == 73 {
                    if file_byte("DerivedCoreProperties.txt", i + 1) == 68 {
                        if file_byte("DerivedCoreProperties.txt", i + 2) == 95 {
                            if file_byte("DerivedCoreProperties.txt", i + 3) == 83 {
                                if file_byte("DerivedCoreProperties.txt", i + 4) == 116 {
                                    if file_byte("DerivedCoreProperties.txt", i + 5) == 97 {
                                        if file_byte("DerivedCoreProperties.txt", i + 6) == 114 {
                                            if file_byte("DerivedCoreProperties.txt", i + 7) == 116 {
                                                if file_byte("DerivedCoreProperties.txt", i + 8) <= 32 {
                                                    start_p = 1
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            if file_byte("DerivedCoreProperties.txt", i + 3) == 67 {
                                if file_byte("DerivedCoreProperties.txt", i + 4) == 111 {
                                    if file_byte("DerivedCoreProperties.txt", i + 5) == 110 {
                                        if file_byte("DerivedCoreProperties.txt", i + 6) == 116 {
                                            if file_byte("DerivedCoreProperties.txt", i + 7) == 105 {
                                                if file_byte("DerivedCoreProperties.txt", i + 8) == 110 {
                                                    if file_byte("DerivedCoreProperties.txt", i + 9) == 117 {
                                                        if file_byte("DerivedCoreProperties.txt", i + 10) == 101 {
                                                            if file_byte("DerivedCoreProperties.txt", i + 11) <= 32 {
                                                                cont_p = 1
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                if start_p == 1 {
                    emit_raw("    pr(83, ")
                    emit_number(lo)
                    emit_raw(", ")
                    emit_number(hi)
                    emit_raw(")\\n")
                    hits = hits + 1
                }
                if cont_p == 1 {
                    emit_raw("    pr(73, ")
                    emit_number(lo)
                    emit_raw(", ")
                    emit_number(hi)
                    emit_raw(")\\n")
                    hits = hits + 1
                }
            }
        }
        // ---- to the end of the line
        while i < n {
            if file_byte("DerivedCoreProperties.txt", i) == 10 { break }
            i = i + 1
        }
        i = i + 1
    }
    emit_raw("}\\n")
    emit_raw("const DCP_HITS_%(k)d: i64 = ")
    emit_number(hits)
    emit_raw("\\nconst DCP_LINES_%(k)d: i64 = ")
    emit_number(lines)
    emit_raw("\\nconst DCP_END_%(k)d: i64 = ")
    emit_number(i)
    emit_raw("\\n")
}
'''


def main():
    check = "--check" in sys.argv
    udata = open(UCD, "rb").read()
    ddata = open(DCP, "rb").read()
    ub = boundaries(udata, CHUNKS_UCD, forbid_after_first=True)
    db = boundaries(ddata, CHUNKS_DCP)
    parts = [HEAD % {
        "nucd": CHUNKS_UCD, "ndcp": CHUNKS_DCP,
        "ubytes": len(udata), "ulines": udata.count(b"\n"),
        "dbytes": len(ddata), "dlines": ddata.count(b"\n"),
    }]
    for k in range(CHUNKS_UCD):
        parts.append(UBLOCK % {"k": k, "start": ub[k], "end": ub[k + 1]})
    for k in range(CHUNKS_DCP):
        parts.append(DBLOCK % {"k": k, "start": db[k], "end": db[k + 1]})

    # main(): the spot checks, then the dump.
    m = ["\nfn main() -> i32 {\n"]
    m.append("    // The whole of both files was walked through, not a part\n")
    m.append("    // of it -- summed over the blocks.\n")
    m.append("    if UCD_END_%d < %d { return 1 }\n" % (CHUNKS_UCD - 1, len(udata)))
    m.append("    if DCP_END_%d < %d { return 2 }\n" % (CHUNKS_DCP - 1, len(ddata)))
    m.append("    if %s != %d { return 3 }\n"
             % (" + ".join("UCD_LINES_%d" % k for k in range(CHUNKS_UCD)),
                sum(1 for line in udata.split(b"\n") if line.count(b";") >= 14)))
    m.append("    if %s < 1 { return 4 }\n"
             % " + ".join("UCD_RANGES_%d" % k for k in range(CHUNKS_UCD)))
    m.append("    if %s < 1 { return 5 }\n"
             % " + ".join("UCD_MAPS_%d" % k for k in range(CHUNKS_UCD)))
    m.append("    if %s < 1 { return 6 }\n"
             % " + ".join("DCP_HITS_%d" % k for k in range(CHUNKS_DCP)))
    for k in range(CHUNKS_UCD):
        m.append("    ucd_dump_%d()\n" % k)
    for k in range(CHUNKS_DCP):
        m.append("    dcp_dump_%d()\n" % k)
    m.append("    return 0\n}\n")
    parts.append("".join(m))

    text = "".join(parts)
    if check:
        if not os.path.exists(OUT):
            print("gen_ucd.fi is missing")
            return 1
        old = open(OUT, encoding="utf-8").read()
        if old != text:
            print("gen_ucd.fi is NOT up to date -- run "
                  "python3 tools/ucd/expand_tables.py")
            return 1
        print("gen_ucd.fi is up to date (%d octets, sha256 %s)"
              % (len(text.encode()), hashlib.sha256(text.encode()).hexdigest()[:16]))
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print("wrote %s: %d octets, %d windows over UnicodeData.txt, %d over "
          "DerivedCoreProperties.txt" % (OUT, len(text.encode()), CHUNKS_UCD, CHUNKS_DCP))
    return 0


if __name__ == "__main__":
    sys.exit(main())
