#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""tools/ucd/expand.py -- writes tools/ucd/ucd_real.fi.

WHAT THIS SCRIPT DOES **NOT** DO: it does not read a single Unicode
category. It knows nothing about the UCD. It repeats ONE `comptime` block
eight times with a different octet window each, and it picks the eight
window boundaries so that each of them lies on a line start and never
between a `<..., First>` line and its `<..., Last>` partner.

WHY EIGHT BLOCKS AND NOT ONE: `compiler/src/comptime.rs` allows
`MAX_STEPS = 2_000_000` executed statements per `comptime` block (SPEC
14.1.comptime, "a comptime must not hang the compiler"). Measured on
2026-08-23 with `tools/ucd/probe2.fi`: a window of 400,065 octets goes
through, 500,000 aborts -- the parse loop costs about five steps per octet.
`UnicodeData.txt` has 2,198,209 octets and therefore does not fit into one
block. A fresh interpreter is built per block (`run_blocks_out`), so the
budget applies per block; eight windows of ~275 KB each stay well inside it.

The whole parsing of the UCD -- hexadecimal code point, the name field, the
general category, the First/Last range convention, and the coalescing of
neighbouring code points with the same category into ranges -- happens
inside the `comptime` blocks, i.e. **in Firn, in the compiler**. This
script only supplies eight numbers.

Usage:
    python3 tools/ucd/expand.py           # write ucd_real.fi
    python3 tools/ucd/expand.py --check   # only check that it is up to date
"""
import bisect
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UCD = os.path.join(HERE, "UnicodeData.txt")
OUT = os.path.join(HERE, "ucd_real.fi")
CHUNKS = 8

# --- the eight windows -------------------------------------------------


def boundaries(data):
    n = len(data)
    starts = []
    forbidden = set()
    off = 0
    for line in data.split(b"\n"):
        starts.append(off)
        fields = line.split(b";")
        if len(fields) > 2 and fields[1].endswith(b", First>"):
            # the NEXT line is the matching `, Last>` -- never split here
            forbidden.add(off + len(line) + 1)
        off += len(line) + 1
    bounds = [0]
    for k in range(1, CHUNKS):
        target = n * k // CHUNKS
        idx = bisect.bisect_left(starts, target)
        while starts[idx] in forbidden:
            idx += 1
        bounds.append(starts[idx])
    bounds.append(n)
    return bounds


# --- the text ----------------------------------------------------------

HEAD = '''// expect_exit: 0
// tools/ucd/ucd_real.fi -- ACCEPTANCE ITEM 6, against the REAL UCD.
//
// GENERATED by tools/ucd/expand.py -- do not edit by hand, edit the script.
// The script contributes eight octet offsets and nothing else; every line of
// Unicode data below is read and interpreted by the COMPILER, at compile
// time, out of `comptime` blocks.
//
// What happens here:
//
//   * `file_size`/`file_byte` (SPEC 14.1.comptime, round 14) read the real
//     `UnicodeData.txt` of the Unicode Character Database, %(bytes)d octets,
//     %(lines)d lines, sha256 in tools/ucd/UnicodeData.sha256.
//   * the `comptime` blocks parse it: field 0 = code point (hexadecimal),
//     field 1 = name, field 2 = general category. The `<..., First>` /
//     `<..., Last>` convention of the UCD is resolved into a real range.
//   * neighbouring code points with the SAME category are coalesced into one
//     range, and every range is emitted as one Firn statement `d(lo, hi, cat)`
//     plus one arm of a lookup function. The category is encoded as
//     `first letter * 256 + second letter`, e.g. `Lu` = 76*256+117 = 19573.
//   * `emit_raw`/`emit_number` (round 13) write that Firn source text, which
//     the SAME compilation run lexes, parses, type-checks and compiles.
//
// The proof is not that it compiles: `ucd_dump()` prints the whole generated
// table, and `tools/ucd/verify.py` holds it against a parser of its own over
// ALL 1,114,112 code points. `tools/ucd/run.sh` drives both and carries a
// counter-check that has to strike.
//
// SECURITY (SPEC 14.1.comptime): the path is relative to the root source
// file, without `..` and without a leading `/` -- which is why the data file
// lies next to this one.

// ---------------------------------------------------------------- output

// Prints "lo hi Xy\\n" -- one line per range of the generated table.
fn d(lo: i64, hi: i64, cat: i64) {
    var buf: [u8; 64] = [0; 64]
    var tmp: [u8; 24] = [0; 24]
    var n: usize = 0
    var m: usize = 0
    var i: usize = 0

    var x: i64 = lo
    if x == 0 {
        tmp[0] = 48
        m = 1
    }
    while x > 0 {
        tmp[m] = (x %% 10) as u8 + 48
        x = x / 10
        m = m + 1
    }
    i = 0
    while i < m {
        buf[n] = tmp[m - 1 - i]
        n = n + 1
        i = i + 1
    }
    buf[n] = 32
    n = n + 1

    m = 0
    x = hi
    if x == 0 {
        tmp[0] = 48
        m = 1
    }
    while x > 0 {
        tmp[m] = (x %% 10) as u8 + 48
        x = x / 10
        m = m + 1
    }
    i = 0
    while i < m {
        buf[n] = tmp[m - 1 - i]
        n = n + 1
        i = i + 1
    }
    buf[n] = 32
    n = n + 1

    buf[n] = (cat / 256) as u8
    n = n + 1
    buf[n] = (cat %% 256) as u8
    n = n + 1
    buf[n] = 10
    n = n + 1
    syscall(1, 1, &buf[0], n as i64)
}
'''

BLOCK = '''
// ------------------------------------------------- block %(k)d: octets %(start)d .. %(end)d
comptime {
    let n: i64 = file_size("UnicodeData.txt")
    var i: i64 = %(start)d
    var seen: i64 = 0
    var ranges: i64 = 0
    var lo: i64 = 0 - 1
    var hi: i64 = 0 - 1
    var cat: i64 = 0
    var pending: i64 = 0 - 1
    emit_raw("fn ucd_dump_%(k)d() {\\n")
    while i < n {
        if i >= %(end)d { break }
        // ---- field 0: the code point, hexadecimal
        var cp: i64 = 0
        var digits: i64 = 0
        while i < n {
            let c: i64 = file_byte("UnicodeData.txt", i)
            var dg: i64 = 0 - 1
            if c >= 48 { if c <= 57 { dg = c - 48 } }
            if c >= 65 { if c <= 70 { dg = c - 55 } }
            if c >= 97 { if c <= 102 { dg = c - 87 } }
            if dg < 0 { break }
            cp = cp * 16 + dg
            digits = digits + 1
            i = i + 1
        }
        // ---- field 1: the name (only its last octets matter)
        i = i + 1
        let name_start: i64 = i
        while i < n {
            if file_byte("UnicodeData.txt", i) == 59 { break }
            i = i + 1
        }
        let name_end: i64 = i
        i = i + 1
        // ---- field 2: the general category, two letters
        let a: i64 = file_byte("UnicodeData.txt", i)
        let b: i64 = file_byte("UnicodeData.txt", i + 1)
        let this_cat: i64 = a * 256 + b
        // ---- the rest of the line
        while i < n {
            if file_byte("UnicodeData.txt", i) == 10 { break }
            i = i + 1
        }
        i = i + 1
        if digits > 0 {
            seen = seen + 1
            // `, First>` (8 octets) and `, Last>` (7 octets) -- the range
            // convention of the UCD, recognised in the file itself.
            var is_first: i64 = 0
            var is_last: i64 = 0
            if name_end - name_start >= 8 {
                if file_byte("UnicodeData.txt", name_end - 8) == 44 {
                    if file_byte("UnicodeData.txt", name_end - 6) == 70 {
                        if file_byte("UnicodeData.txt", name_end - 1) == 62 {
                            is_first = 1
                        }
                    }
                }
            }
            if name_end - name_start >= 7 {
                if file_byte("UnicodeData.txt", name_end - 7) == 44 {
                    if file_byte("UnicodeData.txt", name_end - 5) == 76 {
                        if file_byte("UnicodeData.txt", name_end - 1) == 62 {
                            is_last = 1
                        }
                    }
                }
            }
            var entry_lo: i64 = cp
            var entry_hi: i64 = cp
            var hold: i64 = 0
            if is_first == 1 {
                pending = cp
                hold = 1
            }
            if is_last == 1 {
                entry_lo = pending
                entry_hi = cp
                pending = 0 - 1
            }
            if hold == 0 {
                var merged: i64 = 0
                if lo >= 0 {
                    if cat == this_cat {
                        if entry_lo == hi + 1 {
                            hi = entry_hi
                            merged = 1
                        }
                    }
                }
                if merged == 0 {
                    if lo >= 0 {
                        emit_raw("    d(")
                        emit_number(lo)
                        emit_raw(", ")
                        emit_number(hi)
                        emit_raw(", ")
                        emit_number(cat)
                        emit_raw(")\\n")
                        ranges = ranges + 1
                    }
                    lo = entry_lo
                    hi = entry_hi
                    cat = this_cat
                }
            }
        }
    }
    if lo >= 0 {
        emit_raw("    d(")
        emit_number(lo)
        emit_raw(", ")
        emit_number(hi)
        emit_raw(", ")
        emit_number(cat)
        emit_raw(")\\n")
        ranges = ranges + 1
    }
    emit_raw("}\\n")
    emit_raw("const UCD_RANGES_%(k)d: i64 = ")
    emit_number(ranges)
    emit_raw("\\nconst UCD_LINES_%(k)d: i64 = ")
    emit_number(seen)
    emit_raw("\\nconst UCD_END_%(k)d: i64 = ")
    emit_number(i)
    emit_raw("\\n")
}
'''

# The lookup function is emitted a second time, out of the same ranges --
# once as `d(...)` for the dump, once as an arm of an if-chain.
LOOKUP = '''
// ------------------------------------------- block %(k)d again: the lookup arm
comptime {
    let n: i64 = file_size("UnicodeData.txt")
    var i: i64 = %(start)d
    var lo: i64 = 0 - 1
    var hi: i64 = 0 - 1
    var cat: i64 = 0
    var pending: i64 = 0 - 1
    emit_raw("fn ucd_cat_%(k)d(c: i64) -> i64 {\\n")
    while i < n {
        if i >= %(end)d { break }
        var cp: i64 = 0
        var digits: i64 = 0
        while i < n {
            let c: i64 = file_byte("UnicodeData.txt", i)
            var dg: i64 = 0 - 1
            if c >= 48 { if c <= 57 { dg = c - 48 } }
            if c >= 65 { if c <= 70 { dg = c - 55 } }
            if c >= 97 { if c <= 102 { dg = c - 87 } }
            if dg < 0 { break }
            cp = cp * 16 + dg
            digits = digits + 1
            i = i + 1
        }
        i = i + 1
        let name_start: i64 = i
        while i < n {
            if file_byte("UnicodeData.txt", i) == 59 { break }
            i = i + 1
        }
        let name_end: i64 = i
        i = i + 1
        let a: i64 = file_byte("UnicodeData.txt", i)
        let b: i64 = file_byte("UnicodeData.txt", i + 1)
        let this_cat: i64 = a * 256 + b
        while i < n {
            if file_byte("UnicodeData.txt", i) == 10 { break }
            i = i + 1
        }
        i = i + 1
        if digits > 0 {
            var is_first: i64 = 0
            var is_last: i64 = 0
            if name_end - name_start >= 8 {
                if file_byte("UnicodeData.txt", name_end - 8) == 44 {
                    if file_byte("UnicodeData.txt", name_end - 6) == 70 {
                        if file_byte("UnicodeData.txt", name_end - 1) == 62 {
                            is_first = 1
                        }
                    }
                }
            }
            if name_end - name_start >= 7 {
                if file_byte("UnicodeData.txt", name_end - 7) == 44 {
                    if file_byte("UnicodeData.txt", name_end - 5) == 76 {
                        if file_byte("UnicodeData.txt", name_end - 1) == 62 {
                            is_last = 1
                        }
                    }
                }
            }
            var entry_lo: i64 = cp
            var entry_hi: i64 = cp
            var hold: i64 = 0
            if is_first == 1 {
                pending = cp
                hold = 1
            }
            if is_last == 1 {
                entry_lo = pending
                entry_hi = cp
                pending = 0 - 1
            }
            if hold == 0 {
                var merged: i64 = 0
                if lo >= 0 {
                    if cat == this_cat {
                        if entry_lo == hi + 1 {
                            hi = entry_hi
                            merged = 1
                        }
                    }
                }
                if merged == 0 {
                    if lo >= 0 {
                        emit_raw("    if c < ")
                        emit_number(lo)
                        emit_raw(" { return 0 - 1 }\\n    if c <= ")
                        emit_number(hi)
                        emit_raw(" { return ")
                        emit_number(cat)
                        emit_raw(" }\\n")
                    }
                    lo = entry_lo
                    hi = entry_hi
                    cat = this_cat
                }
            }
        }
    }
    if lo >= 0 {
        emit_raw("    if c < ")
        emit_number(lo)
        emit_raw(" { return 0 - 1 }\\n    if c <= ")
        emit_number(hi)
        emit_raw(" { return ")
        emit_number(cat)
        emit_raw(" }\\n")
    }
    emit_raw("    return 0 - 1\\n}\\n")
}
'''

TAIL = '''
// ------------------------------------------------------------- the roof
comptime {
    emit_raw("fn ucd_dump() {\\n")
    for k in 0..%(chunks)d {
        emit_raw("    ucd_dump_")
        emit_number(k)
        emit_raw("()\\n")
    }
    emit_raw("}\\n")
    emit_raw("fn ucd_category(c: i64) -> i64 {\\n")
    for k in 0..%(chunks)d {
        emit_raw("    let r")
        emit_number(k)
        emit_raw(": i64 = ucd_cat_")
        emit_number(k)
        emit_raw("(c)\\n    if r")
        emit_number(k)
        emit_raw(" >= 0 { return r")
        emit_number(k)
        emit_raw(" }\\n")
    }
    // everything not in the UCD is Cn -- unassigned -- and gets 0.
    emit_raw("    return 0\\n}\\n")
}

fn main() -> i32 {
    // Spot checks against the Unicode standard, written out by hand.
    // `Lu` = 76*256+117 = 19573, `Ll` = 19564, `Nd` = 20068, `Zs` = 23155,
    // `Lo` = 19567, `Cs` = 17267, `So` = 21359, `Co` = 17263, `Zl` = 23148,
    // `Mn` = 19822. 0 means: not in the UCD, i.e. Cn.
    if ucd_category(65) != 19573 { return 1 }
    if ucd_category(97) != 19564 { return 2 }
    if ucd_category(48) != 20068 { return 3 }
    if ucd_category(32) != 23155 { return 4 }
    if ucd_category(769) != 19822 { return 5 }
    if ucd_category(8232) != 23148 { return 6 }
    // 0xD800 -- a surrogate, category Cs
    if ucd_category(55296) != 17267 { return 7 }
    // 0x4E00 and 0xAC00 -- both come out of a `First>`/`Last>` range
    if ucd_category(19968) != 19567 { return 8 }
    if ucd_category(44032) != 19567 { return 9 }
    // 0x20000 -- CJK extension B, also a range
    if ucd_category(131072) != 19567 { return 10 }
    // 0x1F600 -- an emoji, So
    if ucd_category(128512) != 21359 { return 11 }
    // 0x10FFFD -- private use of plane 16, the last line of a range
    if ucd_category(1114109) != 17263 { return 12 }
    // 0x0378 and 0x10FFFF are unassigned
    if ucd_category(888) != 0 { return 13 }
    if ucd_category(1114111) != 0 { return 14 }
    // the whole file was walked through, not a part of it
    if UCD_END_%(last)d < %(bytes)d { return 15 }
    // every line of the file was seen -- summed over the eight blocks
    if %(lines_total)s != %(records)d { return 16 }
    if %(ranges_total)s < 1 { return 17 }
    ucd_dump()
    return 0
}
'''


def build():
    data = open(UCD, "rb").read()
    bounds = boundaries(data)
    lines = data.count(b"\n")
    records = 0
    for line in data.split(b"\n"):
        if len(line.split(b";")) > 2:
            records += 1
    text = HEAD % {"bytes": len(data), "lines": lines}
    for k in range(CHUNKS):
        text += BLOCK % {"k": k, "start": bounds[k], "end": bounds[k + 1]}
    for k in range(CHUNKS):
        text += LOOKUP % {"k": k, "start": bounds[k], "end": bounds[k + 1]}
    text += TAIL % {
        "chunks": CHUNKS,
        "last": CHUNKS - 1,
        "bytes": len(data),
        "records": records,
        "lines_total": " + ".join("UCD_LINES_%d" % k for k in range(CHUNKS)),
        "ranges_total": " + ".join("UCD_RANGES_%d" % k for k in range(CHUNKS)),
    }
    return text


def main():
    text = build()
    if "--check" in sys.argv:
        have = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if have != text:
            print("ucd_real.fi is NOT up to date -- run tools/ucd/expand.py")
            return 1
        print("ucd_real.fi is up to date (%d octets, sha256 %s)"
              % (len(text), hashlib.sha256(text.encode()).hexdigest()[:16]))
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("written: %s (%d octets, %d lines)"
          % (OUT, len(text), text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
