#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
# tools/uiextras/gen_human_test.py -- writes tests/2241_human.fi: the answers ICU
# gives (the expectation is ICU's, not this library's) for a fixed set of inputs
# in the eight languages, as Firn string literals. Run it with PyICU:
#     python3 tools/uiextras/gen_human_test.py > tests/2241_human.fi
import datetime
from decimal import ROUND_HALF_EVEN, Decimal

import icu
from icu import (DateFormat, ListFormatter, Locale, MeasureUnit, NoUnit, NumberFormatter,
                 Precision, RelativeDateTimeFormatter, TimeZone, UNumberUnitWidth as UW,
                 URelativeDateTimeUnit as RU)

LANGS = ["en", "de", "fr", "it", "es", "pl", "cs", "ru"]
GMT = TimeZone.getGMT()
MS = 1790000000000  # 2026-09-21 13:33:20 UTC


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch in '"\\':
            out.append("\\" + ch)
        elif o in (0xA0, 0x202F, 0x2009):
            out.append("\\u{%X}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


lines = []
emit = lines.append
RU_ = {0: RU.SECOND, 1: RU.MINUTE, 2: RU.HOUR, 3: RU.DAY, 4: RU.WEEK, 5: RU.MONTH, 6: RU.YEAR}

rel_cases = [(-300000, 1, -5), (7200000, 2, 2), (-86400000 * 3, 3, -3), (86400000 * 14, 4, 2),
             (-86400000 * 95, 5, -3), (86400000 * 800, 6, 2), (-45000, 0, -45), (-86400000 * 21, 4, -3),
             (-1000 * 60 * 21, 1, -21), (1000 * 60 * 60 * 5, 2, 5)]
bytes_cases = [0, 1, 999, 1000, 2250, 12345678, 999999, 5 * 10 ** 9, 3603294110435203000]
dt_cases = [(4, 2), (4, 1), (3, 1), (2, 2), (2, 1), (1, 9), (9, 2), (9, 1), (4, 9), (3, 9), (2, 9)]
DSTYLE = {4: DateFormat.FULL, 3: DateFormat.LONG, 2: DateFormat.MEDIUM, 1: DateFormat.SHORT}
TSTYLE = {2: DateFormat.MEDIUM, 1: DateFormat.SHORT}
byte_units = [MeasureUnit.createByte(), MeasureUnit.createKilobyte(), MeasureUnit.createMegabyte(),
              MeasureUnit.createGigabyte(), MeasureUnit.createTerabyte(), MeasureUnit.createPetabyte()]

emit("// expect_exit: 0")
emit("// tests/2241_human.fi -- lib/i18n/human.fi in eight languages against ICU %s (CLDR 42)." % icu.ICU_VERSION)
emit("//")
emit("// GENERATED by tools/uiextras/gen_human_test.py: every expected text below is what")
emit("// ICU (PyICU) answers for the same input -- relative times, byte sizes, date and")
emit("// time styles, percent, lists, and the wall clock of two zones read from TZif")
emit("// files. tools/uiextras/check_human.py holds the library against ICU for thousands")
emit("// of random inputs; this file keeps a fixed sample in the test suite (and runs on")
emit("// every build level and on AArch64, where Python is not at hand).")
emit("import i18n.human")
emit("import std.time")
emit("import std.io")
emit("")
emit("static mut bad: i32 = 0")
emit("static mut done: i32 = 0")
emit("")
emit("fn same(what: str, got: str, want: str) {")
emit("    done = done + 1")
emit("    if got != want {")
emit("        bad = bad + 1")
emit("        io.print_line(what)")
emit("        io.print_line(got)")
emit("        io.print_line(want)")
emit("    }")
emit("}")
emit("")
emit("fn wall(ms: i64) -> time.DateTime {")
emit("    return time.civil_from_unix(ms)")
emit("}")
emit("")
emit("fn main() -> i32 {")
emit("    var t: time.DateTime = wall(%d)" % MS)
emit("    t.offset_min = 0 as i32")
for lang in LANGS:
    f = RelativeDateTimeFormatter(Locale(lang))
    emit("    // ---------------------------------------------------------------- %s" % lang)
    for d, u, n in rel_cases:
        want = f.format(0, RU.SECOND) if abs(d) < 5000 else f.formatNumeric(n, RU_[u])
        emit('    same("rel %s %d", human.format_relative("%s", %d), %s)' % (lang, d, lang, d, lit(want)))
    for n in bytes_cases:
        k = 0
        while k < 5 and n >= 1000 ** (k + 1):
            k += 1
        if k > 0:
            v = (Decimal(n) / Decimal(1000 ** k)).quantize(Decimal("0.1"), rounding=ROUND_HALF_EVEN)
            if v >= 1000 and k < 5:
                k += 1
            exact = format(Decimal(n) / Decimal(1000 ** k), "f")
        else:
            exact = str(n)
        nf = NumberFormatter.withLocale(Locale(lang)).unit(byte_units[k]).unitWidth(UW.SHORT).precision(Precision.maxFraction(1))
        emit('    same("bytes %s %d", human.format_bytes("%s", %d, false), %s)' % (lang, n, lang, n, lit(str(nf.formatDecimal(exact.encode())))))
    for ds, ts in dt_cases:
        loc = Locale(lang)
        if ts == 9:
            df = DateFormat.createDateInstance(DSTYLE[ds], loc)
        elif ds == 9:
            df = DateFormat.createTimeInstance(TSTYLE[ts], loc)
        else:
            df = DateFormat.createDateTimeInstance(DSTYLE[ds], TSTYLE[ts], loc)
        df.setTimeZone(GMT)
        emit('    same("dt %s %d %d", human.format_datetime("%s", t, %d as u32, %d as u32), %s)' % (lang, ds, ts, lang, ds, ts, lit(df.format(MS / 1000.0))))
    for fr in (0, 1):
        nf = NumberFormatter.withLocale(Locale(lang)).unit(NoUnit.percent()).precision(Precision.fixedFraction(fr))
        emit('    same("pct %s %d", human.format_percent("%s", 0.5712, %d as u32), %s)' % (lang, fr, lang, fr, lit(str(nf.formatDecimal(b"57.12")))))
    lf = ListFormatter.createInstance(Locale(lang))
    for items in (["Alpha"], ["Alpha", "Bravo"], ["Alpha", "Bravo", "Charlie"], ["Alpha", "Bravo", "Charlie", "Delta"]):
        emit('    same("list %s %d", human.format_list("%s", %s, 124 as u8, false), %s)' % (lang, len(items), lang, lit("|".join(items)), lit(lf.format(items))))
# zones: the wall clock of Vienna and New York (TZif files of the system)
emit("    var vz: time.Tz = time.tz_new()")
emit("    var nz: time.Tz = time.tz_new()")
emit('    let vok: bool = time.tz_load("/usr/share/zoneinfo/Europe/Vienna", &vz) catch false')
emit('    let nok: bool = time.tz_load("/usr/share/zoneinfo/America/New_York", &nz) catch false')
emit("    if vok && nok {")
for lang in ("en", "de", "ru"):
    for (zone, tzname) in (("vz", "Europe/Vienna"), ("nz", "America/New_York")):
        for ms in (MS, 1767225600000 + 3600 * 1000 * 5):  # 2026-09 (summer time), 2026-01-01 05:00 UTC (winter)
            import zoneinfo
            off = int(datetime.datetime.fromtimestamp(ms / 1000, zoneinfo.ZoneInfo(tzname)).utcoffset().total_seconds()) // 60
            df = DateFormat.createDateTimeInstance(DateFormat.LONG, DateFormat.MEDIUM, Locale(lang))
            df.setTimeZone(GMT)
            emit('        same("zone %s %s %d", human.format_in_zone("%s", &%s, %d, 3 as u32, 2 as u32), %s)' % (lang, tzname, ms, lang, zone, ms, lit(df.format((ms + off * 60000) / 1000.0))))
emit("        same(\"offset\", human.format_offset(120 as i32), \"UTC+02:00\")")
emit("        same(\"offset\", human.format_offset(-570 as i32), \"UTC-09:30\")")
emit("        same(\"offset\", human.format_offset(0 as i32), \"UTC\")")
emit("    }")
emit("    time.tz_free(&vz)")
emit("    time.tz_free(&nz)")
emit("    if bad > 0 {")
emit("        io.fmt_print_line(f\"FAIL {bad} of {done}\")")
emit("        return 1")
emit("    }")
emit("    io.fmt_print_line(f\"human: ok ({done} texts)\")")
emit("    return 0")
emit("}")
print("\n".join(lines))
