#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
# examples/codehub/build.py -- writes codehub.fi from codehub.head.fi,
# the texts/SVGs/theme below and codehub.body.fi. Firn has no hex literals
# and a static string needs its octet count, so both are computed here.
import os, re
H = os.path.dirname(os.path.abspath(__file__))
exec(open(os.path.join(H, 'texts.py')).read())
def dec(src):
    return re.sub(r'\b0x([0-9A-Fa-f]{6,8})\b', lambda m: str(int(m.group(1), 16)), src)
head = open(os.path.join(H, 'codehub.head.fi')).read()
body = open(os.path.join(H, 'codehub.body.fi')).read()
out = (dec(head) + "\n// ================================================================ TEXTS\n"
       "// generated by examples/codehub/build.py from texts.py, codehub.theme,\n"
       "// logo.svg and hills.svg -- edit those, then run build.py\n"
       + statics() + "\n" + dec(body))
open(os.path.join(H, 'codehub.fi'), 'w').write(out)
print('codehub.fi', len(out.splitlines()), 'lines')
