// SPDX-License-Identifier: GPL-2.0-only
//! **ROUND 94** — `firnc --test`: find the test functions, run them, report
//! the result MACHINE READABLY (`ACCEPTANCE.md` item 4 criterion A,
//! `TODO-FIRN.md` 0.3).
//!
//! There already was a runner before this round: `tools/testrunner`, written
//! in Rust, which compiles and starts the test PROGRAMS of `tests/` and
//! reports one line per file. That is a runner over programs, not over
//! tests — a `.fi` file with twenty checks in it is one case to it, and when
//! the seventh check fails it can say nothing beyond "the program returned
//! 7".
//!
//! What was missing is the thing every language has: **a test is a
//! FUNCTION**, it is found by an attribute, it runs on its own, it fails on
//! its own, and it says where it failed.
//!
//! ```firn
//! #[test]
//! fn adds_up() {
//!     var a: i32 = 2
//!     a = a + 3 as i32
//!     if a != 5 as i32 { syscall(60, 1, 0, 0, 0, 0, 0) }
//! }
//! ```
//!
//! `firnc --test x.fi` builds a binary out of the file whose `main` is the
//! runner, runs it and hands its output on:
//!
//! ```json
//! {"suite":"firn","total":2,"cases":[
//!   {"name":"adds_up","status":"pass","us":182,"file":"x.fi","line":3,"col":1},
//!   {"name":"overflows","status":"fail","us":162,"file":"x.fi","line":11,"col":9,
//!    "signal":0,"exit":101,"reason":"panic: integer overflow ..."}
//! ],"passed":1,"failed":1,"rate":0.500}
//! ```
//!
//! HOW THE TWO HALVES FIT TOGETHER. The runtime half is Firn source text
//! (`lib/test/runner.fi`) and is embedded here with `include_str!` — the
//! same way the collector runtime has been embedded since round 38. This
//! module writes the second half: one `main` that names every test found,
//! with its name, its function value and the position of its `fn`
//! declaration. Both are lexed and parsed in the SAME run as the program
//! itself, exactly like the source text a `comptime` block produces
//! (`main.rs`, SPEC §6.4). No temporary file, no second compiler run, no
//! external tool.
//!
//! WHY THE POSITION TRAVELS ALONG: a case that dies from a segmentation
//! fault leaves no message behind. Then the position of its declaration is
//! the only true thing that can be said about it, and the compiler is the
//! one that knows it.

use crate::ast::{FnDecl, Program};

/// The runtime half, in Firn. Embedded, so that a test binary needs nothing
/// but the compiler and the assembler.
pub const RUNNER: &str = include_str!("../../lib/test/runner.fi");

/// Output format of the generated runner.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Format {
    Json,
    Tap,
}

impl Format {
    pub fn from_str(s: &str) -> Option<Format> {
        match s {
            "json" => Some(Format::Json),
            "tap" => Some(Format::Tap),
            _ => None,
        }
    }
    fn number(self) -> u32 {
        match self {
            Format::Json => 0,
            Format::Tap => 1,
        }
    }
}

/// Is this function marked `#[test]`?
pub fn is_test(f: &FnDecl) -> bool {
    f.attrs.iter().any(|a| a.name == "test")
}

/// Every test function of the program, in the order they were declared.
pub fn tests_of(prog: &Program) -> Vec<&FnDecl> {
    prog.funcs.iter().filter(|f| is_test(*f)).collect()
}

/// A Firn text literal for `bytes`, plus the number of octets it is long.
/// Everything outside the printable ASCII range is refused rather than
/// escaped: a file name with a line break in it would only produce a puzzle
/// later, and no test of this repository has one.
fn literal(s: &str) -> (String, usize) {
    let mut out = String::from("\"");
    let mut n = 0usize;
    for b in s.bytes() {
        match b {
            b'"' => {
                out.push_str("\\\"");
                n += 1;
            }
            b'\\' => {
                out.push_str("\\\\");
                n += 1;
            }
            0x20..=0x7e => {
                out.push(b as char);
                n += 1;
            }
            _ => {
                out.push('?');
                n += 1;
            }
        }
    }
    out.push('"');
    (out, n)
}

/// The whole generated source text: the runtime plus a `main` that names
/// every test.
///
/// `file_name` is the spelling the diagnostics use for the position of a
/// declaration — since round 93 that is a path that does not name the
/// machine it was built on (`package_world::build_path`).
pub fn harness(tests: &[&FnDecl], names: &[String], format: Format, limit: u32) -> String {
    let mut s = String::new();
    s.push_str(RUNNER);
    s.push_str("\n// ---- generated by compiler/src/testrun.rs (ROUND 94) ----\n");
    s.push_str("fn main() -> i32 {\n");
    s.push_str(&format!(
        "    __test_begin({}, {}, {})\n",
        tests.len(),
        format.number(),
        limit
    ));
    for (i, t) in tests.iter().enumerate() {
        let (nlit, nlen) = literal(&t.name);
        let file = names.get(i).cloned().unwrap_or_default();
        let (flit, flen) = literal(&file);
        // A text literal needs storage of its own; an array of the exact
        // length is the cheapest one there is (no allocation, no collector).
        s.push_str(&format!("    var n{}: [u8; {}] = {}\n", i, nlen.max(1), nlit));
        s.push_str(&format!("    var f{}: [u8; {}] = {}\n", i, flen.max(1), flit));
        s.push_str(&format!(
            "    __test_case((&n{}[0]) as u64, {}, {}, (&f{}[0]) as u64, {}, {}, {})\n",
            i, nlen, t.name, i, flen, t.span.line, t.span.col
        ));
    }
    s.push_str("    return __test_finish()\n}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_text_literal_keeps_its_length() {
        assert_eq!(literal("abc"), ("\"abc\"".to_string(), 3));
        // The escape is TWO characters in the source text and ONE octet in
        // storage -- the array length has to be the second number, otherwise
        // the compiler refuses the literal.
        assert_eq!(literal("a\"b"), ("\"a\\\"b\"".to_string(), 3));
        assert_eq!(literal("a\\b"), ("\"a\\\\b\"".to_string(), 3));
        assert_eq!(literal("a\nb"), ("\"a?b\"".to_string(), 3));
    }

    #[test]
    fn the_runtime_half_is_really_embedded() {
        assert!(RUNNER.contains("fn __test_case("));
        assert!(RUNNER.contains("fn __test_finish()"));
        // No import: the generated text has to be compilable on its own.
        assert!(!RUNNER.contains("\nimport "));
    }
}
