import shutil, sqlite3
shutil.copy('/root/firn-wt-db/tests/data/db/sample.db', '/tmp/e2164.db')
c = sqlite3.connect('/tmp/e2164.db', isolation_level=None)
def q(sql):
    rows = c.execute(sql).fetchall()
    return ";".join("|".join("NULL" if v is None else (("x'" + v.hex().upper() + "'") if isinstance(v, bytes) else str(v)) for v in r) for r in rows)
print(q("SELECT flag FROM cities WHERE id = 10"))
c.execute("INSERT INTO cities(country, name, pop) VALUES ('AT', 'Neustadt', 12345)")
print(q("SELECT max(id) FROM cities"))
c.execute("UPDATE cities SET pop = pop + 1 WHERE country = 'CH'")
print(q("SELECT sum(pop) FROM cities WHERE country = 'CH'"))
c.execute("DELETE FROM cities WHERE id > 100 AND id < 1000")
print(q("SELECT count(*) FROM cities"))
c.execute("CREATE TABLE visits(id INTEGER PRIMARY KEY, city INTEGER, at INTEGER)")
c.execute("INSERT INTO visits(city, at) SELECT id, id * 10 FROM cities")
print(q("SELECT count(*), sum(v.at) FROM visits v JOIN cities c ON c.id = v.city WHERE c.country = 'DE'"))
print(q("SELECT type, name FROM sqlite_master ORDER BY name"))
