# SPDX-License-Identifier: MPL-2.0
# tools/webp/gen_tables.py -- generates the constant tables of lib/webp/webp.fi
# (T_UPD .. T_ACQ and tables_part*) from the reference decoder source printed
# in RFC 6386 ("dixie": vp8_prob_data.h, modemv_data.h, dequant_data.h, unpacked
# into /tmp/dixie/ from the RFC text). Output: tables.fi.part. Brought over from
# the Certus tree unchanged apart from this header.
import re
def carr(path, name):
    s=open(path).read()
    i=s.index(name); j=s.index('=',i); k=s.index('};',j)
    body=s[j+1:k]
    body=re.sub(r'/\*.*?\*/','',body,flags=re.S); body=re.sub(r'//[^\n]*','',body)
    return [int(x) for x in re.findall(r'-?\d+',body)]
D='/tmp/dixie/'
upd=carr(D+'vp8_prob_data.h','k_coeff_entropy_update_probs')
dfl=carr(D+'vp8_prob_data.h','k_default_coeff_probs')
kfb=carr(D+'modemv_data.h','kf_b_mode_probs')
dcq=carr(D+'dequant_data.h','dc_q_lookup')
acq=carr(D+'dequant_data.h','ac_q_lookup')
# strip dimension numbers accidentally captured? arrays start after '=' so fine
assert len(upd)==1056,len(upd); assert len(dfl)==1056,len(dfl); assert len(kfb)==900,len(kfb)
assert len(dcq)==128 and len(acq)==128
blob=bytes(upd)+bytes(dfl)+bytes(kfb)+b''.join(v.to_bytes(2,'little') for v in dcq)+b''.join(v.to_bytes(2,'little') for v in acq)
print(len(blob))
def esc(b): return ''.join('\\x%02x'%c for c in b)
out=['// GENERATED by gen_tables.py from the reference decoder of RFC 6386','// (vp8_prob_data.h, modemv_data.h, dequant_data.h). Do not edit.','// Layout: coeff update probs 1056, default coeff probs 1056,','// kf_bmode_probs 900, dc_q 128 x u16le, ac_q 128 x u16le.','',
'const T_UPD: usize = 0','const T_DEF: usize = 1056','const T_KFB: usize = 2112','const T_DCQ: usize = 3012','const T_ACQ: usize = 3268','const T_LEN: usize = %d'%len(blob),'',
'fn tables_fill(p: u64) {']
CH=1024; parts=[]
for n,o in enumerate(range(0,len(blob),CH)):
    ch=blob[o:o+CH]
    out.append('    tables_part%d(p, %d)'%(n,o)); parts.append((n,o,ch))
out.append('}')
for n,o,ch in parts:
    out+=['','#[no_gc]','fn tables_part%d(p: u64, at: usize) {'%n,'    var t: [u8; %d] = b"%s"'%(len(ch),esc(ch)),'    var i: usize = 0','    while i < %d {'%len(ch),'        *((p + (at + i) as u64) as *mut u8) = t[i]','        i = i + 1','    }','}']
open('tables.fi.part','w').write('\n'.join(out)+'\n')
