globalThis.fail=0;
function ck(n,c){ if(!c && globalThis.fail===0) globalThis.fail=n; }
ck(1, Object.hasOwn({a:1},"a") && !Object.hasOwn({a:1},"b"));
ck(2, JSON.stringify(Object.fromEntries([["a",1],["b",2]]))==='{"a":1,"b":2}');
ck(3, Object.getOwnPropertySymbols({[Symbol.iterator]:1}).length===1);
ck(4, Object.getOwnPropertyDescriptors({a:1}).a.value===1);
ck(5, JSON.stringify(Object.keys(Object.groupBy([1,2,3,4],x=>x%2)))==='["1","0"]');
var oo={}; oo.__defineGetter__("g",function(){return 5;}); ck(6, oo.g===5);
ck(7, typeof oo.__lookupGetter__("g")==="function");
ck(8, Object.getPrototypeOf([])===Array.prototype && [].__proto__===Array.prototype);
ck(9, Math.clz32(1)===31 && Math.clz32(0)===32);
ck(10, Math.imul(3,4)===12 && Math.imul(-5,12)===-60);
ck(11, Math.fround(1.1)===1.100000023841858 && Math.fround(0)===0);
ck(12, Math.asin(1)===Math.PI/2 && Math.acos(1)===0);
ck(13, Math.log1p(0)===0 && Math.expm1(0)===0);
ck(14, Math.sinh(0)===0 && Math.cosh(0)===1 && Math.tanh(0)===0);
ck(15, Math.asinh(0)===0 && Math.acosh(1)===0 && Math.atanh(0)===0);
ck(16, Math.random()>=0 && Math.random()<1);
ck(17, Math.LOG2E===1/Math.LN2 && Math.SQRT1_2===Math.sqrt(0.5));
ck(18, (123.456).toExponential(2)==="1.23e+2");
ck(19, (123.456).toPrecision(5)==="123.46");
ck(20, (0).toExponential(2)==="0.00e+0" && (123456).toPrecision(2)==="1.2e+5");
ck(21, (function(){try{(1).toPrecision(0)}catch(e){return e instanceof RangeError}return false})());
ck(22, "  x  ".trimStart()==="x  " && "  x  ".trimEnd()==="  x");
ck(23, "abc".localeCompare("abd")<0 && "a".toLocaleUpperCase()==="A");
ck(24, "abc".normalize()==="abc" && "abc".normalize("NFC")==="abc");
ck(25, (function(){try{"a".normalize("X")}catch(e){return e instanceof RangeError}return false})());
ck(26, String.fromCodePoint(97,98)==="ab" && String.raw`a\nb`==="a\\nb");
ck(27, "x".anchor("y")==='<a name="y">x</a>' && "x".bold()==="<b>x</b>");
ck(28, "ab".isWellFormed()===true);
ck(29, [1,2,3].at(-1)===3 && [1,2,3].at(0)===1 && [1,2,3].at(9)===undefined);
ck(30, [[1,[2]],3].flat(2).join()==="1,2,3" && [1,2].flatMap(x=>[x,x]).join()==="1,1,2,2");
ck(31, [1,2,3].findLast(x=>x<3)===2 && [1,2,3].findLastIndex(x=>x<3)===1);
ck(32, [1,2,3,4,5].copyWithin(0,3).join()==="4,5,3,4,5");
ck(33, [...[7,8].keys()].join()==="0,1" && [...[7,8].values()].join()==="7,8");
ck(34, JSON.stringify([...[7,8].entries()])==="[[0,7],[1,8]]");
ck(35, [1,2,3].toReversed().join()==="3,2,1" && [3,1,2].toSorted().join()==="1,2,3");
ck(36, [1,2,3].with(1,9).join()==="1,9,3" && [1,2,3].toSpliced(1,1,7,8).join()==="1,7,8,3");
ck(37, Array.prototype[Symbol.iterator]===Array.prototype.values);
ck(38, Array.prototype[Symbol.unscopables].flat===true);
ck(39, Symbol.for("k")===Symbol.for("k") && Symbol.keyFor(Symbol.for("k"))==="k");
ck(40, Symbol("d").description==="d" && Symbol().description===undefined);
ck(41, typeof Symbol.toStringTag==="symbol" && typeof Symbol.hasInstance==="symbol");
ck(42, Object.prototype.toString.call(Math)==="[object Math]");
ck(43, Object.prototype.toString.call(new Map())==="[object Map]");
ck(44, Object.prototype.toString.call([])==="[object Array]");
var mm=new Map([[1,"a"],[2,"b"]]);
ck(45, [...mm.keys()].join()==="1,2" && [...mm.values()].join()==="a,b");
ck(46, JSON.stringify([...mm])==='[[1,"a"],[2,"b"]]');
ck(47, mm.getOrInsert(3,"c")==="c" && mm.get(3)==="c");
ck(48, mm.getOrInsertComputed(4,k=>k*10)===40);
ck(49, [...Map.groupBy([1,2,3],x=>x%2).keys()].join()==="1,0");
var s1=new Set([1,2]), s2=new Set([2,3]);
ck(50, s1.union(s2).size===3 && s1.intersection(s2).size===1);
ck(51, s1.difference(s2).size===1 && s1.symmetricDifference(s2).size===2);
ck(52, new Set([1]).isSubsetOf(s1) && s1.isSupersetOf(new Set([1])));
ck(53, new Set([9]).isDisjointFrom(s1));
ck(54, [...new Set([5,6]).entries()].length===2);
var wk=new WeakMap(), key={};
ck(55, wk.set(key,1)===wk && wk.get(key)===1 && wk.has(key) && wk.delete(key) && !wk.has(key));
ck(56, (function(){try{new WeakMap().set(1,2)}catch(e){return e instanceof TypeError}return false})());
var wr=new WeakRef(key); ck(57, wr.deref()===key);
ck(58, typeof new FinalizationRegistry(function(){}).register==="function");
ck(59, Reflect.has({a:1},"a") && Reflect.get({a:5},"a")===5);
ck(60, Reflect.ownKeys({a:1,b:2}).join()==="a,b");
ck(61, Reflect.construct(Array,[3]).length===3 && Reflect.apply(Math.max,null,[1,5,2])===5);
ck(62, Reflect.defineProperty({},"a",{value:1})===true);
ck(63, Reflect.getPrototypeOf([])===Array.prototype);
ck(64, Reflect.isExtensible({})===true && Reflect.preventExtensions({})===true);
ck(65, encodeURIComponent("a b/")==="a%20b%2F" && encodeURI("a b/")==="a%20b/");
ck(66, decodeURIComponent("%41")==="A" && decodeURI("%41")==="A");
ck(67, (function(){try{decodeURI("%")}catch(e){return e instanceof URIError}return false})());
ck(68, escape("~")==="%7E" && unescape("%41")==="A");
ck(69, Error.isError(new TypeError("x")) && !Error.isError({}));
ck(70, new AggregateError([1,2],"m").errors.join()==="1,2");
ck(71, new Error("m",{cause:7}).cause===7);
ck(72, typeof $262==="object" && $262.global===globalThis);
ck(73, (function(){return typeof arguments[Symbol.iterator];})()==="function");
ck(74, (function(){return [...arguments].join();})(1,2)==="1,2");
ck(75, [..."abc"].join("-")==="a-b-c");
class HasI { static [Symbol.hasInstance](x){ return x===1; } }
ck(76, (1 instanceof HasI) && !(2 instanceof HasI));
ck(77, typeof [][Symbol.iterator]().next==="function");
ck(78, Object.prototype.toString.call([][Symbol.iterator]())==="[object Array Iterator]");
ck(79, Math.f16round(1.5)===1.5 && Math.sumPrecise([1,2,3])===6);
ck(80, Object.getOwnPropertyDescriptor(Symbol.prototype,"description").get!==undefined);
