globalThis.fail=0;
function ck(n,c){ if(!c && globalThis.fail===0) globalThis.fail=n; }
ck(1, /a+/.test("baaa") && !/x/.test("baaa"));
ck(2, /a+/.exec("baaa")[0]==="aaa" && /a+/.exec("baaa").index===1);
ck(3, "2019-01-02".replace(/(\d+)-(\d+)-(\d+)/,"$3.$2.$1")==="02.01.2019");
ck(4, "a1b22c333".match(/\d+/g).join("|")==="1|22|333");
ck(5, "a,b;c".split(/[,;]/).join("-")==="a-b-c");
ck(6, "hello".search(/l+/)===2 && "hello".search(/z/)===-1);
ck(7, "HeLLo".match(/l+/i)[0]==="LL");
ck(8, /(?<y>\d{4})-(?<m>\d{2})/.exec("2020-05").groups.y==="2020");
ck(9, "2020-05".replace(/(?<y>\d{4})-(?<m>\d{2})/,"$<m>/$<y>")==="05/2020");
ck(10, /^ab$/m.test("x\nab") && !/^ab$/.test("x\nab"));
ck(11, /a.c/s.test("a\nc") && !/a.c/.test("a\nc"));
ck(12, [..."a1b2".matchAll(/(\w)(\d)/g)].map(function(m){return m[1]+m[2];}).join()==="a1,b2");
ck(13, "aaa".replace(/a/g,function(m,i){return i;})==="012");
ck(14, /\bfoo\b/.test("a foo b") && !/\bfoo\b/.test("afoob"));
ck(15, /(?=x)./.exec("xy")[0]==="x" && !/(?!x)./.test("x"));
ck(16, /(?<=a)b/.test("ab") && !/(?<=c)b/.test("ab"));
ck(17, /(?<!c)b/.test("ab"));
ck(18, /[^a-c]/.test("d") && !/[^a-c]/.test("b"));
ck(19, /[\d\s]/.test(" ") && /\S/.test("x") && !/\S/.test(" "));
ck(20, /a{2,3}/.exec("aaaa")[0]==="aaa" && /a+?/.exec("aaa")[0]==="a");
ck(21, /a{2}/.test("aa") && !/a{3}/.test("aa"));
var g=/a/g;
ck(22, g.lastIndex===0 && g.test("aa") && g.lastIndex===1 && g.test("aa") && g.lastIndex===2 && !g.test("aa") && g.lastIndex===0);
ck(23, String(/ab+c/gi)==="/ab+c/gi" && /ab/.source==="ab" && /ab/gi.flags==="gi");
ck(24, /(a)|(b)/.exec("b")[2]==="b" && /(a)|(b)/.exec("b")[1]===undefined);
ck(25, "abc".split("").join("|")==="a|b|c" && "".split("").length===0);
ck(26, /(a*)*b/.test("aaab") && /^(a+)+$/.test("aaaa"));
ck(27, "A".match(/a/i).index===0 && RegExp("a\\d","g").exec("xa5")[0]==="a5");
ck(28, (function(){try{new RegExp("(","")}catch(e){return e instanceof SyntaxError}return false})());
ck(29, (function(){try{new RegExp("a","q")}catch(e){return e instanceof SyntaxError}return false})());
ck(30, /A/.test("A") && /\x41/.test("A"));
ck(31, /\u{1F600}/u.test("\uD83D\uDE00"));
ck(32, /^.$/u.test("\uD83D\uDE00") && !/^.$/.test("\uD83D\uDE00"));
ck(33, /(a)\1/.test("aa") && !/(a)\1/.test("ab"));
ck(34, /(?<w>a)\k<w>/.test("aa"));
ck(35, "abc".replace("b","X")==="aXc" && "a-b-c".replaceAll("-","+")==="a+b+c");
ck(36, "aaa".replaceAll("a","$&$&")==="aaaaaa");
ck(37, "x".replace(/x/,"$$")==="$" && "abc".replace(/b/,"[$`|$']")==="a[a|c]c");
ck(38, /y/y.test("y") && !(function(){var re=/y/y; re.lastIndex=1; return re.test("ya");})());
ck(39, "a1b2".split(/(\d)/).join("|")==="a|1|b|2|");
ck(40, "aaa".split(/a/).length===4);
ck(41, /[a-c]+/.exec("xxabcxx")[0]==="abc");
ck(42, /a|ab/.exec("ab")[0]==="a");
ck(43, /(ab)+/.exec("ababab")[1]==="ab");
ck(44, /^\s*$/.test("  \t ") && !/^\s*$/.test(" x "));
ck(45, /\W/.test("!") && !/\W/.test("a"));
ck(46, RegExp.prototype.exec.call(/a/,"ba")[0]==="a");
ck(47, /a/d.exec("ba").indices[0].join()==="1,2");
ck(48, typeof /a/[Symbol.match]==="function" && typeof /a/[Symbol.replace]==="function");
ck(49, /a/.hasIndices===false && /a/d.hasIndices===true);
ck(50, /\p{L}/u.test("A") && !/\p{L}/u.test("1"));
ck(51, "abc".match(/(b)(c)/).slice(1).join()==="b,c");
ck(52, "test".replace(/t/g,"T")==="TesT");
ck(53, new RegExp(/a/g).flags==="g" && new RegExp(/a/g,"i").flags==="i");
ck(54, "aXbXc".split("X",2).join()==="a,b");
ck(55, /[]/.test("a")===false && /[^]/.test("a")===true);
ck(56, "abc".match(/z/g)===null && "abc".match(/z/)===null);
ck(57, /a/g[Symbol.match]("aa").length===2);
ck(58, [..."ab".matchAll(/./g)].length===2);
ck(59, (function(){try{"a".matchAll(/a/)}catch(e){return e instanceof TypeError}return false})());
ck(60, /(a)(?:b)(c)/.exec("abc").length===3);
