#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
# Generates the vector block of tests/2050_ed25519.fi with Python's `cryptography`
# (an Ed25519 nobody here wrote). RFC 8032 section 7.1 TEST 1-3 are asserted
# against the literals of the RFC, so the generator itself is checked.
#   python3 tools/appkit/gen_ed25519_vectors.py > /tmp/vectors.fi
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization

L = 2 ** 252 + 27742317777372353535851937790883648493


def vec(seed_hex, msg):
    sk = Ed25519PrivateKey.from_private_bytes(bytes.fromhex(seed_hex))
    pk = sk.public_key().public_bytes(serialization.Encoding.Raw,
                                      serialization.PublicFormat.Raw)
    return pk.hex(), sk.sign(msg).hex()


RFC = {
    '9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60':
        ('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a',
         'e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b'),
    '4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb':
        ('3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c',
         '92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00'),
    'c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7':
        ('fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025',
         '6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a'),
}

cases = [
    ('9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60', b''),
    ('4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb', bytes.fromhex('72')),
    ('c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7', bytes.fromhex('af82')),
    (bytes((i * 7 + 3) & 255 for i in range(32)).hex(), bytes((i * 13 + 5) & 255 for i in range(200))),
]
print('// generated by tools/appkit/gen_ed25519_vectors.py -- do not edit by hand')
print('const NVEC: usize = %d' % len(cases))
for n, (seed, msg) in enumerate(cases):
    pk, sig = vec(seed, msg)
    if seed in RFC:
        assert (pk, sig) == RFC[seed], 'RFC 8032 literal mismatch'
    print('const V%d_SEED: str = "%s"' % (n, seed))
    print('const V%d_PUB: str = "%s"' % (n, pk))
    print('const V%d_MSG: str = "%s"' % (n, msg.hex()))
    print('const V%d_SIG: str = "%s"' % (n, sig))
pk, sig = vec(*cases[0])
s = int.from_bytes(bytes.fromhex(sig)[32:], 'little')
mal = bytes.fromhex(sig)[:32] + (s + L).to_bytes(32, 'little')
print('// the signature of V0 with S replaced by S+L: same point equation, not canonical')
print('const MALLEABLE_SIG: str = "%s"' % mal.hex())
