# SPDX-License-Identifier: GPL-2.0-only
# Eigenstaendiges Werkzeug: NICHT Teil des Compilers und keine Abhaengigkeit
# von ihm. Ohne externe Crates (nur std), damit `cargo build` offline laeuft.
[workspace]

[package]
name = "testrunner"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "testrunner"
path = "src/main.rs"

[dependencies]

[profile.release]
opt-level = 2
