#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Produces lib/dom/ua_data.fi out of lib/dom/ua.css.

A WORKBENCH, NOT A PRODUCT: the default stylesheet is CSS and is kept as
CSS (lib/dom/ua.css) so it stays readable and comparable with the
"Rendering" section of the HTML standard. This script only packs it into a
Firn string literal, whose length has to be written out (SPEC 8).

Comments are dropped and runs of whitespace are folded to one space -- the
CSS tokeniser would do that anyway, and it keeps the literal small.

Usage:  python3 tools/domb1/gen_ua.py
"""

import os
import re


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    source = os.path.join(root, "lib", "dom", "ua.css")
    target = os.path.join(root, "lib", "dom", "ua_data.fi")

    text = open(source, encoding="utf-8").read()
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"\s+", " ", text).strip()
    raw = text.encode("utf-8")
    if b'"' in raw or b"\\" in raw:
        raise SystemExit("the stylesheet must not contain a quote or a backslash")

    out = []
    out.append('// lib/dom/ua_data.fi -- GENERATED by tools/domb1/gen_ua.py.')
    out.append('// DO NOT EDIT BY HAND. The source is lib/dom/ua.css.')
    out.append('//')
    out.append('// The DEFAULT STYLESHEET of the engine, packed into a string literal.')
    out.append('// Without it every element would be `display: inline` without margins,')
    out.append('// and a computed style that says that is worth nothing.')
    out.append('')
    out.append('import html.mem')
    out.append('')
    out.append('export { ua_bytes, UA_LENGTH }')
    out.append('')
    out.append('const UA_LENGTH: usize = %d' % len(raw))
    out.append('')
    out.append('#[no_gc]')
    out.append('fn ua_bytes(out: *mut mem.Buf) {')
    out.append('    var t: [u8; %d] = "%s"' % (len(raw), text))
    out.append('    var i: usize = 0')
    out.append('    while i < %d {' % len(raw))
    out.append('        mem.buf_push(out, t[i])')
    out.append('        i = i + 1')
    out.append('    }')
    out.append('}')
    with open(target, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s (%d bytes of CSS)" % (target, len(raw)))


if __name__ == "__main__":
    main()
