#!/usr/bin/env python3
"""tools/tuples/gen.py -- random programs full of tuples (round TUPLES).

Every program declares a handful of functions whose parameters and results are
tuples of random element types (integers of every width, floats, bool, nested
tuples, a struct), calls them with deterministic values and folds everything
that comes out into one checksum, which `main` prints as a decimal number.
Both compilers, every build level and the aarch64 target have to print the
same number -- a tuple passed or returned the wrong way (register class,
alignment, the hidden result pointer) changes the checksum.

usage: gen.py SEED > program.fi
"""
import random
import sys

INTS = ["i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64"]
FLOATS = ["f32", "f64"]
SCALARS = INTS + FLOATS + ["bool"]


class Gen:
    def __init__(self, seed):
        self.r = random.Random(seed)
        self.lines = []
        self.counter = 0

    def fresh(self, base):
        self.counter += 1
        return "%s%d" % (base, self.counter)

    def scalar(self):
        return self.r.choice(SCALARS)

    def ty(self, depth=0):
        k = self.r.random()
        if depth < 2 and k < 0.30:
            n = self.r.randint(2, 4)
            return "(" + ", ".join(self.ty(depth + 1) for _ in range(n)) + ")"
        if k < 0.38:
            return "Pt"
        return self.scalar()

    def tuple_ty(self):
        n = self.r.randint(2, 5)
        return "(" + ", ".join(self.ty(1) for _ in range(n)) + ")"

    # a value expression of type t, built from small constants
    def value(self, t):
        if t == "Pt":
            return "Pt { a: %d, b: %d }" % (self.r.randint(-50, 50), self.r.randint(0, 200))
        if t.startswith("("):
            return "(" + ", ".join(self.value(x) for x in self.split(t)) + ")"
        if t == "bool":
            return self.r.choice(["true", "false"])
        if t in FLOATS:
            return "%d.%d" % (self.r.randint(0, 99), self.r.randint(0, 9))
        lo, hi = {
            "i8": (-100, 100), "u8": (0, 200), "i16": (-3000, 3000), "u16": (0, 6000),
            "i32": (-90000, 90000), "u32": (0, 90000), "i64": (-9000000, 9000000), "u64": (0, 9000000),
        }[t]
        return "%d" % self.r.randint(lo, hi)

    def split(self, t):
        inner = t[1:-1]
        out, depth, cur = [], 0, ""
        for ch in inner:
            if ch == "(":
                depth += 1
            if ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                out.append(cur.strip())
                cur = ""
            else:
                cur += ch
        out.append(cur.strip())
        return out

    # statements that fold the value `expr` of type t into `acc` (an i64 variable)
    def fold(self, t, expr, acc, ind):
        if t == "Pt":
            return ["%s%s = %s *%% 31 +%% (%s).a as i64 *%% 7 +%% (%s).b as i64" % (ind, acc, acc, expr, expr)]
        if t.startswith("("):
            out = []
            for i, x in enumerate(self.split(t)):
                out += self.fold(x, "(%s).%d" % (expr, i), acc, ind)
            return out
        if t == "bool":
            return ["%sif %s { %s = %s *%% 31 +%% 1 } else { %s = %s *%% 31 +%% 2 }" % (ind, expr, acc, acc, acc, acc)]
        if t in FLOATS:
            return ["%s%s = %s *%% 31 +%% (%s * 4.0) as i64" % (ind, acc, acc, expr)]
        return ["%s%s = %s *%% 31 +%% (%s) as i64" % (ind, acc, acc, expr)]


def program(seed):
    g = Gen(seed)
    out = []
    out.append("// generated by tools/tuples/gen.py, seed %d" % seed)
    out.append("import std.io")
    out.append("")
    out.append("struct Pt { a: i16, b: u8 }")
    out.append("")
    funcs = []
    for _ in range(g.r.randint(3, 6)):
        name = g.fresh("f")
        nparams = g.r.randint(1, 4)
        params = [(g.fresh("p"), g.tuple_ty() if g.r.random() < 0.8 else g.scalar()) for _ in range(nparams)]
        ret = g.tuple_ty()
        funcs.append((name, params, ret))
        out.append("fn %s(%s) -> %s {" % (name, ", ".join("%s: %s" % p for p in params), ret))
        # the result: built from the parameters where the types fit, else from constants
        parts = []
        for x in g.split(ret):
            cands = [p for p in params if p[1] == x]
            if cands and g.r.random() < 0.7:
                parts.append(g.r.choice(cands)[0])
            else:
                parts.append(g.value(x))
        out.append("    return (%s)" % ", ".join(parts))
        out.append("}")
        out.append("")
    out.append("fn main() -> i32 {")
    out.append("    var acc: i64 = 17")
    for name, params, ret in funcs:
        args = ", ".join(g.value(t) for _, t in params)
        v = g.fresh("v")
        out.append("    let %s = %s(%s)" % (v, name, args))
        out += g.fold(ret, v, "acc", "    ")
        # take it apart as well, when the first element is a scalar
        first = g.split(ret)[0]
        if first in SCALARS:
            a = g.fresh("a")
            rest = ", ".join("_" for _ in g.split(ret)[1:])
            out.append("    let (%s, %s) = %s" % (a, rest, v))
            out += g.fold(first, a, "acc", "    ")
    out.append("    io.fmt_print_line(f\"{acc}\")")
    out.append("    return 0")
    out.append("}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.stdout.write(program(int(sys.argv[1])))
