#!/usr/bin/env python3
"""Generates tests/data/kdf-vectors.json: BLAKE2b (RFC 7693) and Argon2id (RFC 9106)
vectors for lib/std/crypto/{blake2b,argon2}.fi.

Independent oracles only: Python hashlib.blake2b, the C reference tool /usr/bin/argon2,
and the RFC 9106 section 5.3 vector (secret + associated data, which the CLI cannot do).
Deterministic: inputs are a fixed byte pattern, no clock, no randomness.

    python3 tools/kdf/gen_vectors.py > tests/data/kdf-vectors.json
"""
import hashlib
import json
import subprocess
import sys


def pat(n, seed):
    return bytes((i * 7 + seed) & 255 for i in range(n))


def blake2b_cases():
    out = []
    # RFC 7693 appendix A: BLAKE2b-512("abc")
    abc = hashlib.blake2b(b"abc").hexdigest()
    assert abc.startswith("ba80a53f981c4d0d6a2797b69f12f6e9"), abc
    out.append({"id": "rfc7693-abc", "in": b"abc".hex(), "outlen": 64, "out": abc})
    for n in [0, 1, 2, 3, 63, 64, 65, 127, 128, 129, 255, 256, 257, 1000]:
        for ol in (1, 16, 32, 64):
            d = pat(n, n % 13)
            out.append({"id": f"len{n}-out{ol}", "in": d.hex(), "outlen": ol,
                        "out": hashlib.blake2b(d, digest_size=ol).hexdigest()})
    return out


def cli_argon2id(pw, salt, t, kib, p, outlen):
    r = subprocess.run(["/usr/bin/argon2", salt.decode(), "-id", "-t", str(t), "-k", str(kib),
                        "-p", str(p), "-l", str(outlen), "-r"], input=pw, capture_output=True)
    assert r.returncode == 0, r.stderr
    return r.stdout.decode().strip()


def argon2_cases():
    out = []
    # RFC 9106 section 5.3, Argon2id test vector
    out.append({
        "id": "rfc9106-5.3", "t": 3, "m": 32, "p": 4, "outlen": 32,
        "pw": (b"\x01" * 32).hex(), "salt": (b"\x02" * 16).hex(),
        "secret": (b"\x03" * 8).hex(), "ad": (b"\x04" * 12).hex(),
        "tag": "0d640df58d78766c08c037a34a8b53c9d01ef0452d75b65eb52520e96b01e659",
        "oracle": "RFC 9106",
    })
    # (t, KiB, lanes, outlen, password, salt); salt >= 8 printable octets
    grid = [
        (1, 8, 1, 32, b"a", b"saltsalt"),
        (1, 8, 1, 4, b"p", b"saltsalt"),
        (2, 16, 1, 32, b"password", b"somesaltsomesalt"),
        (3, 64, 2, 32, b"password", b"somesaltsomesalt"),
        (1, 256, 4, 16, b"correct horse battery staple", b"0123456789abcdef"),
        (2, 100, 3, 24, b"password", b"somesaltsomesalt"),      # m is not a multiple of 4p
        (3, 1024, 1, 32, b"x" * 100, b"salt-with-length-24-ab!!"),
        (2, 4096, 2, 64, b"password", b"somesaltsomesalt"),
        (4, 512, 5, 33, b"Pa55w0rd!", b"\x41" * 32),
        (1, 16, 2, 100, b"password", b"somesaltsomesalt"),      # tag longer than 64: H' chain
        (3, 8192, 1, 32, b"password", b"somesaltsomesalt"),
        (3, 65536, 1, 32, b"password", b"somesaltsomesalt"),    # the FirnChat/Certus setting: 64 MiB, 3 passes
    ]
    for (t, kib, p, ol, pw, salt) in grid:
        out.append({"id": f"cli-t{t}-m{kib}-p{p}-l{ol}", "t": t, "m": kib, "p": p, "outlen": ol,
                    "pw": pw.hex(), "salt": salt.hex(), "secret": "", "ad": "",
                    "tag": cli_argon2id(pw, salt, t, kib, p, ol), "oracle": "/usr/bin/argon2"})
    return out


json.dump({"kdf_vectors": 1,
           "note": "Generated by tools/kdf/gen_vectors.py. blake2b: hashlib; argon2id: C reference CLI + RFC 9106 5.3.",
           "blake2b": blake2b_cases(), "argon2id": argon2_cases()},
          sys.stdout, indent=1)
sys.stdout.write("\n")
