#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# tools/gen_gctext.sh -- produces lib/firnc1/gctext.fi from lib/gc/gc.fi.
#
# WHY: `firnc0` embeds the collector runtime with `include_str!`
# (compiler/src/gc.rs, LAUFZEIT). Firn has no `include_str` -- the
# honest equivalent is this generated file: the same text, packed as
# u64 words (8 bytes per word, little-endian), so that the
# self-hosting compiler can pull it in without file access.
# After a change to lib/gc/gc.fi run this script and
# commit lib/firnc1/gctext.fi along with it.
#
# ROUND 53: what is packed is the CONCATENATION of gc.fi + gcvec.fi + gcmap.fi,
# exactly as `runtime_source` in gc.rs puts it together. The collections
# hang at the end and are only unpacked along when the program needs
# them -- which is why there are two lengths: GCTEXT_N (only gc.fi) and
# GCTEXT_ALL (with the collections).
set -euo pipefail
cd "$(dirname "$0")/.."
# ROUND B1: an optional target path. `tools/fixpoint.sh` needs to compare the
# CONTENT of lib/firnc1/gctext.fi with what the script would produce today,
# and it must not write into the tree to find that out.
export GCTEXT_TARGET="${1:-lib/firnc1/gctext.fi}"
python3 - <<'PYEOF'
import os
target = os.environ.get('GCTEXT_TARGET', 'lib/firnc1/gctext.fi')
kern = open('lib/gc/gc.fi','rb').read()
samml = open('lib/gc/gcvec.fi','rb').read() + open('lib/gc/gcmap.fi','rb').read()
src = kern + samml
n = len(kern)
alle = len(src)
words = []
for i in range(0, alle, 8):
    chunk = src[i:i+8].ljust(8, b'\0')
    words.append(int.from_bytes(chunk, 'little'))
out = []
out.append('// lib/firnc1/gctext.fi -- GENERATED by tools/gen_gctext.sh from')
out.append('// lib/gc/gc.fi. DO NOT EDIT BY HAND.')
out.append('//')
out.append('// The source of the collector runtime as data (round 34): `firnc0`')
out.append('// embeds it with `include_str!`; this stage carries it as u64')
out.append('// words inside its own text. `gctext_write` unpacks it again --')
out.append('// the driver pulls it in as an extra module as soon as a program')
out.append('// contains a `gc class` (runtime_source in gc.rs).')
out.append('import rt')
out.append('')
out.append('export { GCTEXT_N, GCTEXT_ALL, gctext_write }')
out.append('')
out.append('// Length of the core (lib/gc/gc.fi) in octets.')
out.append('const GCTEXT_N: u64 = %d' % n)
out.append('// Length including the collections (gcvec.fi + gcmap.fi) behind it.')
out.append('const GCTEXT_ALL: u64 = %d' % alle)
out.append('')
out.append('// `with_collections` decides whether GcVec/GcMap get unpacked too --')
out.append('// exactly like the third parameter of runtime_source.')
out.append('fn gctext_write(b: *mut rt.Buf, with_collections: bool) {')
out.append('    var limit: u64 = GCTEXT_N')
out.append('    if with_collections {')
out.append('        limit = GCTEXT_ALL')
out.append('    }')
out.append('    var w: [u64; %d] = [' % len(words))
for i in range(0, len(words), 10):
    out.append('        ' + ' '.join(str(x) + ',' for x in words[i:i+10]))
out.append('    ]')
out.append('    var written: u64 = 0')
out.append('    var i: usize = 0')
out.append('    while i < %d {' % len(words))
out.append('        let v: u64 = w[i]')
out.append('        var k: u64 = 0')
out.append('        while k < 8 {')
out.append('            if written >= limit {')
out.append('                return')
out.append('            }')
out.append('            rt.buf_push(b, ((v >> (k * 8)) & 255) as u8)')
out.append('            written = written + 1')
out.append('            k = k + 1')
out.append('        }')
out.append('        i = i + 1')
out.append('    }')
out.append('}')
open(target,'w').write('\n'.join(out) + '\n')
print(target + ':', alle, 'bytes (core', n, ') as', len(words), 'words')
PYEOF