#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Produces the Rc test programs out of the ONE implementation
# (tests/modules/rc.fi, symlink lib/rc/rc.fi) and the test bodies in
# lib/rc/parts/.
#
# Why copy them together at all instead of 'import modules.rc'?
# Stage 0 does not resolve generic templates across module boundaries: neither
# 'rc.RefCount[T]' in type position nor 'rc.rc_new[T](..)' in a call
# can be compiled ("expected '=' after the name ..." resp. "only
# direct function names can be called"). lib/str already uses exactly the
# same solution (tools/strlib/expand.py): the library stands
# once in the tree and is put into the test programs verbatim.
# Run with:  bash lib/rc/gen_tests.sh
set -euo pipefail
cd "$(dirname "$0")/../.."
MOD=tests/modules/rc.fi

erzeuge() {                 # $1 = body, $2 = target file
    local rumpf="$1" ziel="$2"
    {
        head -1 "$rumpf"
        echo "// GENERATED by lib/rc/gen_tests.sh: line 1 and the body from"
        echo "// $rumpf, with tests/modules/rc.fi VERBATIM in between."
        cat "$MOD"
        tail -n +2 "$rumpf"
    } > "$ziel"
}

for r in lib/rc/parts/5*.fi; do
    erzeuge "$r" "tests/$(basename "$r")"
    echo "  tests/$(basename "$r")"
done
for r in lib/rc/parts/neg_*.fi; do
    n=$(basename "$r"); n=${n#neg_}
    erzeuge "$r" "tests/neg/$n"
    echo "  tests/neg/$n"
done

# Round 47: the same mechanism for `Arc[T]` (lib/rc/arc.fi).
MOD=lib/rc/arc.fi
for r in lib/rc/parts/83*.fi; do
    erzeuge "$r" "tests/$(basename "$r")"
    echo "  tests/$(basename "$r")"
done
for r in lib/rc/parts/negarc_*.fi; do
    n=$(basename "$r"); n=${n#negarc_}
    erzeuge "$r" "tests/neg/$n"
    echo "  tests/neg/$n"
done
